name: Deploy to Render

on:
  push:
    branches:
      - Vulnerabilidad  # Asegúrate de que coincide con el nombre exacto de tu rama

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render Deploy Hook
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
