name: Deploy to Render

on:
  push:
    branches:
      - main  # o la rama que desees vigilar

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Trigger Render deploy
        env:
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          curl -X POST https://api.render.com/v1/services/$RENDER_SERVICE_ID/deploys \
            -H 'Authorization: Bearer '$RENDER_API_KEY \
            -H 'Accept: application/json' \
            -H 'Content-Type: application/json'
