name: Veracode Pipeline Scan & Fix

on:
  push:
    branches: [ "Vulnerabilidad" ]
  pull_request:
    branches: [ "Vulnerabilidad" ]

jobs:
  pipeline_scan:
    runs-on: ubuntu-latest
    name: Veracode Pipeline Scan
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Package source code
        run: zip -r verademo.zip . -x '*.git*'

      - name: Run Veracode Pipeline Scan
        id: pipeline-scan
        uses: veracode/Veracode-pipeline-scan-action@v1.0.18
        with:
          vid: ${{ secrets.VERACODE_API_ID }}
          vkey: ${{ secrets.VERACODE_API_KEY }}
          file: verademo.zip
          debug: 1
          fail_build: false

      - name: Upload scan results
        uses: actions/upload-artifact@v4
        with:
          name: veracode-scan-results
          path: results.json

  veracode_fix:
    runs-on: ubuntu-latest
    needs: pipeline_scan
    if: ${{ always() }}
    name: Veracode Fix
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
  
      - name: Download scan results
        uses: actions/download-artifact@v4
        with:
          name: veracode-scan-results
  
      - name: Validate results.json
        run: |
          if [ ! -s results.json ]; then
            echo "Error: results.json is empty or missing."
            exit 1
          fi
  
      - name: Run Veracode Fix
        uses: veracode/veracode-fix@main
        with:
          inputFile: results.json
          vid: ${{ secrets.VERACODE_API_ID }}
          vkey: ${{ secrets.VERACODE_API_KEY }}
          token: ${{ secrets.GITHUB_TOKEN }}
          source_base_path_1: "./:./"
          language: python
          prComment: true
          fixType: single
          debug: true
