# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will initiate a Veracode Static Analysis Pipeline scan, return a results.json and convert to SARIF for upload as a code scanning alert

name: Veracode Static Analysis Pipeline Scan

on:
  push:
    branches: [ "Vulnerabilidad" ]
  pull_request:
    branches: [ "Vulnerabilidad" ]
  schedule:
    - cron: '25 3 * * 0,1,2,3,4'

permissions:
  contents: read

jobs:
  build-and-pipeline-scan:
    permissions:
      contents: read
      security-events: write
      actions: read
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Zip application
        run: zip -r veracode-scan-target.zip ./ -x '*.git*'

      - name: Download Veracode Pipeline Scan
        run: curl --silent --show-error --fail -O https://downloads.veracode.com/securityscan/pipeline-scan-LATEST.zip

      - name: Unzip Veracode Pipeline Scan
        run: unzip -o pipeline-scan-LATEST.zip

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 8
          distribution: 'temurin'

      - name: Run Veracode Pipeline Scan
        run: |
          java -jar pipeline-scan.jar \
            --veracode_api_id "${{ secrets.VERACODE_API_ID }}" \
            --veracode_api_key "${{ secrets.VERACODE_API_KEY }}" \
            --fail_on_severity="Very High, High" \
            --file veracode-scan-target.zip
        continue-on-error: true

      - name: Convert pipeline scan output to SARIF format
        id: convert
        uses: veracode/veracode-pipeline-scan-results-to-sarif@ff08ae5b45d5384cb4679932f184c013d34da9be
        with:
          pipeline-results-json: results.json

      - name: Upload SARIF to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: veracode-results.sarif
