name: Veracode Static Analysis Pipeline Scan

on:
  push:
    branches: [ "Vulnerabilidad" ]
  pull_request:
    branches: [ "Vulnerabilidad" ]

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  pipeline-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Package source code
        run: zip -r veracode-scan-target.zip . -x '*.git*'

      - name: Run Veracode Pipeline Scan
        uses: veracode/Veracode-pipeline-scan-action@v1.0.18
        with:
          vid: ${{ secrets.VERACODE_API_ID }}
          vkey: ${{ secrets.VERACODE_API_KEY }}
          file: veracode-scan-target.zip
          fail_on_severity: "Very High, High"
          json_output: true
          json_output_file: results.json
          filtered_json_output_file: filtered_results.json
          fail_build: true
          project_name: "Repo_TestPrac"
          project_url: "https://github.com/ysa8a/Repo_TestPrac"
          project_ref: ${{ github.ref }}

      - name: Subir resultados de Veracode
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: veracode-results
          path: filtered_results.json

